### ISSUE TITLE
API V3 is no longer supported. Use API V4 instead

### ISSUE THREAD

**Issue by ayoubeddafali** [ciricihq/gitlab-sonar-scanner#27]
Please, 

I have this error when running sonar-scanner, it is something related to Gitlab API V3. 

``
Caused by: java.io.FileNotFoundException: https://gitlab.com/api/v3/projects
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:336)
	at com.talanlabs.gitlab.api.v3.http.GitLabHTTPRequestor.toPaged(GitLabHTTPRequestor.java:144)
	at com.talanlabs.gitlab.api.v3.services.GitLabAPIProjects.getProjects(GitLabAPIProjects.java:101)
	at com.talanlabs.gitlab.api.v3.services.GitLabAPIProjects.getProjects(GitLabAPIProjects.java:43)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.getGitLabProject(GitLabApiV3Wrapper.java:90)
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV3Wrapper.init(GitLabApiV3Wrapper.java:63)
 ``

**Comment by elboletaire** [comment]
First off, you should create an issue specifying all the versions of the packages. Which includes:

- Version of our docker container (sha version prefered)
- Version of gitlab
- Version of the gitlab plugin
- Version of sonarqube

BTW, like said in #23, this seems like a problem with the way you're integrating the gitlab plugin, and nothing with our container.

So, please, try to run the sonarqube scanner alone (without containers, and reducing the amount of plugins and extras), and try to isolate the problem.
